print("Nama: AZZAM")
print("NIM: 123456789")
print("Halo! Ini adalah kode yang dibuat di Windows.")
print("Dan sekarang berjalan di dalam Ubuntu Server via Git!")
print("Saya sedang belajarAdministrasi dan Integrasi")